### ISSUE TITLE
Retinanet run: Package 'networkx' requires a different Python: 3.8.10 not in '>=3.9'

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/cm4mlops#384] opened 2024-10-17 13:16 UTC
run cmd:
```
cm run script --tags=run-mlperf,inference,_submission,_r4.1-dev --submitter="MLCommons" --hw_name=gh_ubuntu_x86  --model=retinanet  --implementation=nvidia    --backend=tensorrt    --category=datacenter    --scenario=Offline --test_query_count=500 --target_qps=1 --docker_dt=yes --docker_it=no --docker_cm_repo=anandhu-eng@cm4mlops --adr.compiler.tags=gcc --device=cuda --results_dir=$HOME/gh_action_results --submission_dir=$HOME/gh_action_submissions --clean  --docker --quiet --docker_cm_repo_branch=sdxl_accuracy_fixes --docker_cache=no --use_dataset_from_host=yes
```

error:
```
* cm run script "get generic-python-lib _package.networkx"
392.4 DEBUG:root:            - Number of scripts found: 1
392.4 DEBUG:root:            - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib,_package.networkx
392.4 DEBUG:root:              - Number of cached script outputs found: 0
392.4 DEBUG:root:            - Found script::get-generic-python-lib,94b62a682bc44791 in /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-generic-python-lib
392.4 DEBUG:root:              Prepared variations: _package.networkx
392.4 DEBUG:root:            - Checking if script execution is already cached ...
392.4 DEBUG:root:              - Prepared explicit variations: _package.networkx
392.4 DEBUG:root:              - Prepared variations: _package.networkx
392.4 DEBUG:root:              - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib,install,generic,_package.networkx,deps-python-version-3.8.10,deps-python-non-virtual
392.4 DEBUG:root:            - Creating new "cache" script artifact in the CM local repository ...
392.4 DEBUG:root:              - Tags: tmp,get,generic-python-lib,install,generic,_package.networkx,deps-python-version-3.8.10,deps-python-non-virtual,script-artifact-94b62a682bc44791
392.4 DEBUG:root:            - Changing to /home/cmuser/CM/repos/local/cache/db3d5aa956294c76
392.4 DEBUG:root:            - Checking dependencies on other CM scripts:
392.4 INFO:root:            * cm run script "detect os"
392.4 DEBUG:root:              - Number of scripts found: 1
392.4 DEBUG:root:              - Found script::detect-os,863735b7db8c44fc in /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os
392.4 DEBUG:root:              - Running preprocess ...
392.4 DEBUG:root:              - Running native script "/home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/run.sh" from temporal script "tmp-run.sh" in "/home/cmuser/CM/repos/local/cache/db3d5aa956294c76" ...
392.4 INFO:root:                   ! cd /home/cmuser/CM/repos/local/cache/db3d5aa956294c76
392.4 INFO:root:                   ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/run.sh from tmp-run.sh
392.5 INFO:root:                   ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/customize.py
392.5 DEBUG:root:              - Running postprocess ...
392.5 INFO:root:              - running time of script "detect-os,detect,os,info": 0.04 sec.
392.5 INFO:root:            * cm run script "detect cpu"
392.5 DEBUG:root:              - Number of scripts found: 1
392.5 DEBUG:root:              - Found script::detect-cpu,586c8a43320142f7 in /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-cpu
392.5 DEBUG:root:              - Checking dependencies on other CM scripts:
392.5 INFO:root:              * cm run script "detect os"
392.5 DEBUG:root:                - Number of scripts found: 1
392.5 DEBUG:root:                - Found script::detect-os,863735b7db8c44fc in /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os
392.5 DEBUG:root:                - Running preprocess ...
392.5 DEBUG:root:                - Running native script "/home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/run.sh" from temporal script "tmp-run.sh" in "/home/cmuser/CM/repos/local/cache/db3d5aa956294c76" ...
392.5 INFO:root:                     ! cd /home/cmuser/CM/repos/local/cache/db3d5aa956294c76
392.5 INFO:root:                     ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/run.sh from tmp-run.sh
392.5 INFO:root:                     ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-os/customize.py
392.5 DEBUG:root:                - Running postprocess ...
392.5 INFO:root:                - running time of script "detect-os,detect,os,info": 0.05 sec.
392.5 DEBUG:root:              - Processing env after dependencies ...
392.5 DEBUG:root:              - Running preprocess ...
392.5 DEBUG:root:              - Running native script "/home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-cpu/run.sh" from temporal script "tmp-run.sh" in "/home/cmuser/CM/repos/local/cache/db3d5aa956294c76" ...
392.5 INFO:root:                   ! cd /home/cmuser/CM/repos/local/cache/db3d5aa956294c76
392.5 INFO:root:                   ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-cpu/run.sh from tmp-run.sh
392.7 INFO:root:                   ! call "postprocess" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/detect-cpu/customize.py
392.7 DEBUG:root:              - Running postprocess ...
392.7 INFO:root:              - running time of script "detect,cpu,detect-cpu,info": 0.20 sec.
392.7 INFO:root:            * cm run script "get python3"
392.7 DEBUG:root:              - Number of scripts found: 1
392.7 DEBUG:root:              - Searching for cached script outputs with the following tags: -tmp,get,python3
392.7 DEBUG:root:                - Number of cached script outputs found: 1
392.7 DEBUG:root:              - Found script::get-python3,d0b5dd74373f4a62 in /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-python3
392.7 DEBUG:root:              - Checking if script execution is already cached ...
392.7 DEBUG:root:                - Searching for cached script outputs with the following tags: -tmp,get,python3,python,get-python,get-python3
392.7 DEBUG:root:                - Found cached script output: /home/cmuser/CM/repos/local/cache/c40e0a49e1954177
392.7 DEBUG:root:                - Checking prehook dependencies on other CM scripts:
392.7 DEBUG:root:                  - Loading state from cached entry ...
392.7 INFO:root:                 ! load /home/cmuser/CM/repos/local/cache/c40e0a49e1954177/cm-cached-state.json
392.7 DEBUG:root:                - Checking posthook dependencies on other CM scripts:
392.7 DEBUG:root:                - Checking post dependencies on other CM scripts:
392.7 INFO:root:              - running time of script "get,python,python3,get-python,get-python3": 0.00 sec.
392.7 INFO:root:Path to Python: /usr/bin/python3
392.7 INFO:root:Python version: 3.8.10
392.7 INFO:root:            * cm run script "get generic-python-lib _pip"
392.7 DEBUG:root:              - Number of scripts found: 1
392.7 DEBUG:root:              - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib,_pip
392.7 DEBUG:root:                - Number of cached script outputs found: 1
392.7 DEBUG:root:              - Found script::get-generic-python-lib,94b62a682bc44791 in /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-generic-python-lib
392.7 DEBUG:root:                Prepared variations: _pip
392.7 DEBUG:root:              - Checking if script execution is already cached ...
392.7 DEBUG:root:                - Prepared explicit variations: _pip
392.7 DEBUG:root:                - Prepared variations: _pip
392.7 DEBUG:root:                - Searching for cached script outputs with the following tags: -tmp,get,generic-python-lib,install,generic,_pip,deps-python-version-3.8.10,deps-python-non-virtual
392.7 DEBUG:root:                - Found cached script output: /home/cmuser/CM/repos/local/cache/52336b4cb7994f22
392.7 DEBUG:root:              - Checking dynamic dependencies on other CM scripts:
392.7 DEBUG:root:              - Processing env after dependencies ...
392.7 DEBUG:root:                - Checking prehook dependencies on other CM scripts:
392.7 DEBUG:root:                  - Loading state from cached entry ...
392.7 INFO:root:                 ! load /home/cmuser/CM/repos/local/cache/52336b4cb7994f22/cm-cached-state.json
392.7 DEBUG:root:                - Checking posthook dependencies on other CM scripts:
392.7 DEBUG:root:                - Checking post dependencies on other CM scripts:
392.7 INFO:root:              - running time of script "get,install,generic,generic-python-lib": 0.00 sec.
392.7 DEBUG:root:            - Processing env after dependencies ...
392.7 DEBUG:root:            - Running preprocess ...
392.7 DEBUG:root:                - Running native script "/home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-generic-python-lib/run.sh" from temporal script "tmp-run.sh" in "/home/cmuser/CM/repos/local/cache/db3d5aa956294c76" ...
392.7 INFO:root:                     ! cd /home/cmuser/CM/repos/local/cache/db3d5aa956294c76
392.7 INFO:root:                     ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-generic-python-lib/run.sh from tmp-run.sh
392.8 INFO:root:                     ! call "detect_version" from /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-generic-python-lib/customize.py
392.8 DEBUG:root:                - Running detect_version ...
392.8 DEBUG:root:            - Running native script "/home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-generic-python-lib/install.sh" from temporal script "tmp-run.sh" in "/home/cmuser/CM/repos/local/cache/db3d5aa956294c76" ...
392.8 INFO:root:                 ! cd /home/cmuser/CM/repos/local/cache/db3d5aa956294c76
392.8 INFO:root:                 ! call /home/cmuser/CM/repos/anandhu-eng@cm4mlops/script/get-generic-python-lib/install.sh from tmp-run.sh
392.8 
392.8 /usr/bin/python3 -m pip install "networkx" --extra-index-url https://download.pytorch.org/whl/cpu
393.2 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
395.5 Collecting networkx
395.5   Downloading https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)
395.9 ERROR: Package 'networkx' requires a different Python: 3.8.10 not in '>=3.9'
395.9 
395.9 
395.9             Extra PIP CMD:  --upgrade --no-deps --force-reinstall
395.9 
395.9             Detected version: 0.16.0a0
395.9 
395.9               Extra PIP CMD: 
395.9 
395.9               Detected version: 10.4.0
395.9 
395.9                 Extra PIP CMD:  --extra-index-url https://download.pytorch.org/whl/cpu
395.9 
395.9 
395.9 CM error: Portable CM script failed (name = get-generic-python-lib, return code = 256)

```

**Comment by arjunsuresh** [comment] 2024-10-30 17:17
This is fixed now - the problem is with installation of torch_cpu which is avoided now.

**Closed by arjunsuresh** 2024-10-30 17:17 UTC
