### ISSUE TITLE
intel conda channel not available

### ISSUE THREAD

**Issue by ZhangSean42** [mlcommons/cm4mlops#229] opened 2024-09-17 15:20 UTC
I want to run mlperf in my local env, AMD cpu + ubuntu22.04
I run this command
`cm run script --tags=run-mlperf,inference,_find-performance,_full,_r4.1-dev \
   --model=resnet50 \
   --implementation=reference \
   --framework=onnxruntime \
   --category=edge \
   --scenario=Offline \
   --execution_mode=test \
   --device=cpu  \
   --quiet \
   --test_query_count=1000`
only to be greeted with this
`CM/repos/local/cache/08247ed5ad504c81/miniconda3/bin/conda install -y -c intel mkl-include
Collecting package metadata (current_repodata.json): failed
UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>
The channel is not accessible or is invalid.`
I add two channels, but it still doesn't work.
`CM/repos/local/cache/08247ed5ad504c81/miniconda3/bin/conda config --show channels
channels:- intel  - https://software.repos.intel.com/python/conda/  - defaults`

**Comment by arjunsuresh** [comment] 2024-09-17 23:16
Unfortunately the Intel conda channel just disappeared. The latest Intel MLPerf results are using a docker. We'll make them available via CM starting next week.

**Comment by ktotam1** [comment] 2024-11-06 14:12
any updates on this? i there a link to the docker images?

**Comment by ktotam1** [comment] 2024-11-06 15:38
hello, I was able to fix this by installing cm4mlops in editable mode and changing 
script/install-generic-conda-package/customize.py
this isnt the proper enterprise way to do it but i replaced 
install_cmd += " -c "+env['CM_CONDA_PKG_SRC'] + " "
by 
install_cmd += " -c -c https://software.repos.intel.com/python/conda/ --override-channels "
I would need to dig deeper to find out where CM CONDA PKG SRC is set but this hacky thing works for me for now

**Comment by ktotam1** [comment] 2024-11-06 16:14
Ok no worries, thanks for the speedy reply :)

**Comment by arjunsuresh** [comment] 2024-11-06 16:19
You're welcome 😊

**Comment by arjunsuresh** [comment] 2024-11-13 22:47
Closing this as the issue is resolved now.

**Closed by arjunsuresh** 2024-11-13 22:47 UTC
Labels: mlperf-inference
